---
- name: Install Nova-Compute
- hosts: compute_group
  gather_facts: yes
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - handlers/main.yml
  tasks:
    - name: Install Nova Compute packages
      apt: pkg=nova-compute state=present

    - name: Copy Nova Compute config files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - {src: "nova.conf-compute.j2", dest: "/etc/nova/nova.conf" }
        - {src: "nova-compute.conf.j2", dest: "/etc/nova/nova-compute.conf" }

    - name: Restart Nova Compute Services
      service: name=nova-compute state=restarted
