---
- name: Setup NFS Client
- hosts: compute_group
  gather_facts: yes
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - handlers/main.yml
  tasks:
    - name: Install NFSv4 Client package
      apt: pkg=nfs-common state=present

    - name: Test for /etc/fstab entry
      shell: grep -c "^172.16.0.10" /etc/fstab || true
      register: test_entry

    - name: Add Nova instances folder to FSTAB
      lineinfile:
        path: /etc/fstab
        line: 172.16.0.10:/ /var/lib/nova/instances nfs4 defaults 0 0
      when: test_entry.stdout == "0"

    - name: Remount device
      shell: mount -av

    # This enable the ‘execute/search’ bit on your shared directory to allow qemu to be able to use the images within the directories
    - name: Change Nova instances folder permissions.
      file: path=/var/lib/nova/instances owner=nova group=nova recurse=yes
