# -*- mode: ruby -*-
# vi: set ft=ruby :

# WARNING: This Vagrantfile is for development purposes only. It is intended to
# bootstrap required services - such as mysql and rabbit - into a reliably
# accessible VM, rather than forcing the engineer to install and manage these
# services manually. This Vagrantfile is not intended to assist in provisioning
# Ironic. For that, please use the bifrost project.

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = 'ubuntu/trusty64'

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.enable :pip
    config.cache.enable :apt
  end

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  #config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../", "/home/vagrant/samsara", create:true

  # Fake root
  config.vm.synced_folder "../fake_root/etc/samsara", "/etc/samsara", create:true
  config.vm.synced_folder "../fake_root/var/lib/samsara", "/var/lib/samsara", create:true
  config.vm.synced_folder "../fake_root/var/lock/samsara", "/var/lock/samsara", create:true
  config.vm.synced_folder "../fake_root/var/log/samsara", "/var/log/samsara", create:true
  config.vm.synced_folder "../fake_root/var/run/samsara", "/var/run/samsara", create:true

  config.vm.define 'samsara' do |samsara|
    samsara.vm.provider :virtualbox do |vb|
      vb.name = "openstack-samsara-local"
      vb.gui = true
      vb.customize ['modifyvm', :id, '--memory', '2048', '--cpuexecutioncap', '25']
      vb.customize ['modifyvm', :id, '--cpus', '2']
    end

    samsara.vm.network 'private_network', ip: '192.168.99.11' # It goes to 11.

    samsara.vm.provision 'ansible' do |ansible|
      ansible.verbose = 'vvvv'
      ansible.playbook = 'samsara-client.yaml'
      ansible.extra_vars = {
          ip: '192.168.99.11'
      }
      ansible.groups = {
          "controller_group" => ["samsara-server"],
          "compute_group" => ["samsara-client"],
          "all_groups:children" => ["samsara-client", "samsara-server"]
      }

    end
  end
end
