---
- name: Install Neutron-Compute
- hosts: compute_group
  gather_facts: yes
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - handlers/main.yml
  tasks:
    - name: Install Neutron Compute packages
      apt:
        state: present
        pkg:
          - neutron-linuxbridge-agent

    - name: Copy Neutron config files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
      - { src: "neutron-compute.conf.j2", dest: "/etc/neutron/neutron.conf" }
      - { src: "linuxbridge-compute.ini.j2", dest: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini"}
      - { src: "nova.conf-compute.j2", dest: "/etc/nova/nova.conf" }

    - name: Restart Nova Compute and Neutron services
      service: name={{ item }} state=restarted
      with_items:
          - nova-compute
          - neutron-linuxbridge-agent 
