---
###############################################################################
# This ansible playbook installs all supporting software necessary to run the
# OpenStack service locally into the vagrant VM attached. Its intent is to provide
# a quickstart development environment that doesn't pollute an engineer's own
# machine.
#
- hosts: all
  gather_facts: yes
  become: yes
  user: vagrant
  vars_files:
      - vars/main.yml
  handlers: 
    - include: handlers/main.yml
  pre_tasks:
    # Make sure our VM's software is ~@Latest
    - name: Apt Update
      apt: update_cache=yes
          upgrade=dist
          cache_valid_time=86400

    - name: Adjusting Locale
      shell: locale-gen pt_BR.UTF-8

    # Add OpenStack Repositories
    - name: Install some deps packages
      become: yes
      apt: 
        state: present
        pkg:
          - software-properties-common
          - ubuntu-cloud-keyring

   # - name: Add OpenStack Repositories
   #   shell: add-apt-repository cloud-archive:{{ openstack_release }}

    - name: Update packages
      apt: update_cache=yes upgrade=dist cache_valid_time=86400
    
    - name: Install Openstack Client
      apt:
        state: present
        pkg:
          - python3-openstackclient
        
  tasks:
       - include: tasks/common.yml
       - include: tasks/credentials.yml
  
  post_tasks:
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

###############################################################################"
- hosts: controllers_group
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    -  include: tasks/chrony-controller.yml
    -  include: tasks/database-server.yml
    -  include: tasks/rabbitmq-server.yml
    -  include: tasks/memcached.yml
    -  include: tasks/etcd.yml
    -  include: tasks/keystone.yml
    -  include: tasks/glance.yml
    -  include: tasks/placement.yml
    -  include: tasks/nova-controller.yml
    -  include: tasks/neutron-controller.yml
#    -  include: tasks/horizon.yml
    -  include: tasks/nfs-server.yml

- hosts: compute_group
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    -  include: tasks/chrony-compute.yml
    -  include: tasks/nova-compute.yml
    -  include: tasks/neutron-compute.yml
    -  include: tasks/nfs-client.yml
    -  include: tasks/libvirt.yml
    -  include: tasks/compute_node_live_migration_config.yml

- hosts: controller
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    -  include: tasks/create-networks.yml
    -  include: tasks/create-instances.yml

