---
###############################################################################
# This ansible playbook installs all supporting software necessary to run the
# OpenStack service locally into the vagrant VM attached. Its intent is to provide
# a quickstart development environment that doesn't pollute an engineer's own
# machine.
#
- hosts: all
  gather_facts: no
  become: yes
  user: vagrant
  pre_tasks:
    - name: 'install python'
      raw: 'apt-get install -y python'

- hosts: all
  gather_facts: yes
  become: yes
  user: vagrant
  vars_files:
      - vars/main.yml
  handlers: 
    - include: handlers/main.yml
  pre_tasks:
    # Make sure our VM's software is ~@Latest
    - name: Apt Update
      apt: update_cache=yes
          upgrade=dist
          cache_valid_time=86400

    - name: Adjusting Locale
      shell: locale-gen pt_BR.UTF-8

    - name: Check if packages need to be autoremoved
      command: apt-get --dry-run autoremove
      register: check_autoremove
      changed_when: False

    - name: Autoremove unused packages
      command: apt-get -y autoremove
      when: "'packages will be REMOVED' in check_autoremove.stdout"

    # - name: Remove cgroup-lite package
    #   apt: name=cgroup-lite state=absent


    # # Reboot if required.
    # - name: Reboot system (cgroup fix)
    #   sudo: yes
    #   command: shutdown -r now 'Rebooting system'
    #   async: 0
    #   poll: 0
    #   ignore_errors: true
    #   register: rebooted

    # Reboot if required.
    # - name: Reboot system if required
    #   sudo: yes
    #   command: shutdown -r now 'Rebooting to complete system upgrade'
    #        removes=/var/run/reboot-required
    #   async: 0
    #   poll: 0
    #   ignore_errors: true
    #   register: rebooted

    # - name: Wait for VM Reboot.
    #   sudo: no
    #   local_action: wait_for
    #                 port=2222
    #                 host="{{ ansible_default_ipv4.address }}"
    #                 # search_regex=OpenSSH
    #                 delay=10
    #                 timeout=120
    #   when: rebooted.changed

    # - name: Wait for VM Reboot.
    #   sudo: no
    #   local_action: wait_for host={{ inventory_hostname }}
    #                 state=started
    #                 delay=10
    #                 timeout=60
    #   when: rebooted.changed

    # Add OpenStack Repositories
    - name: Install some deps packages
      become: yes
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - software-properties-common
        - ubuntu-cloud-keyring

    - name: Add OpenStack Repositories
      shell: add-apt-repository cloud-archive:{{ openstack_release }}

    - name: Update packages
      apt: update_cache=yes upgrade=dist cache_valid_time=86400

    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item]['ansible_all_ipv4_addresses'][1] }} {{item}}" state=present
      when: hostvars[item]['ansible_all_ipv4_addresses'][1] is defined
      with_items: "{{ groups.all }}"

  tasks:
       - include: tasks/common.yml
       - include: tasks/credentials.yml
###############################################################################"
- hosts: controller
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    -  include: tasks/database-server.yml
      # tags: db-server
    -  include: tasks/rabbitmq-server.yml
      # tags: rabbitmq-server
    -  include: tasks/memcached.yml
      # tags: memcached
    -  include: tasks/etcd.yml
      # tags: etcd
    -  include: tasks/keystone.yml
      # tags: keystone
    -  include: tasks/glance.yml
      # tags: glance
    - include: tasks/placement.yml
      # tags: placement
    -  include: tasks/nova-controller.yml
      # tags: nova-controller
#       -  include: tasks/horizon.yml
#       -  include: tasks/nfs-server.yml
#       -  include: tasks/demo-project.yml

# - hosts: compute_group
#   sudo: true
#   vars_files:
#       - vars.yml
#   tasks:
#       - include: tasks/postgresql-client.yml
#       - include: tasks/nova-compute.yml
#       - include: tasks/nfs-client.yml
