---
###############################################################################
# This ansible playbook installs all supporting software necessary to run the
# OpenStack service locally into the vagrant VM attached. Its intent is to provide
# a quickstart development environment that doesn't pollute an engineer's own
# machine.
#
- hosts: all
  gather_facts: yes
  become: yes
  user: vagrant
  vars_files:
      - vars/main.yml
  handlers: 
    - include: handlers/main.yml
  pre_tasks:
    # Make sure our VM's software is ~@Latest
    - name: Apt Update
      apt: update_cache=yes
          upgrade=dist
          cache_valid_time=86400

    - name: Adjusting Locale
      shell: locale-gen pt_BR.UTF-8

    - name: Check if packages need to be autoremoved
      command: apt-get --dry-run autoremove
      register: check_autoremove
      changed_when: False

    - name: Autoremove unused packages
      command: apt-get -y autoremove
      when: "'packages will be REMOVED' in check_autoremove.stdout"

    # - name: Remove cgroup-lite package
    #   apt: name=cgroup-lite state=absent


    # # Reboot if required.
    # - name: Reboot system (cgroup fix)
    #   sudo: yes
    #   command: shutdown -r now 'Rebooting system'
    #   async: 0
    #   poll: 0
    #   ignore_errors: true
    #   register: rebooted

    # Reboot if required.
    # - name: Reboot system if required
    #   sudo: yes
    #   command: shutdown -r now 'Rebooting to complete system upgrade'
    #        removes=/var/run/reboot-required
    #   async: 0
    #   poll: 0
    #   ignore_errors: true
    #   register: rebooted

    # - name: Wait for VM Reboot.
    #   sudo: no
    #   local_action: wait_for
    #                 port=2222
    #                 host="{{ ansible_default_ipv4.address }}"
    #                 # search_regex=OpenSSH
    #                 delay=10
    #                 timeout=120
    #   when: rebooted.changed

    # - name: Wait for VM Reboot.
    #   sudo: no
    #   local_action: wait_for host={{ inventory_hostname }}
    #                 state=started
    #                 delay=10
    #                 timeout=60
    #   when: rebooted.changed

    # Add OpenStack Repositories
    - name: Install some deps packages
      become: yes
      apt: 
        state: present
        pkg:
          - software-properties-common
          - ubuntu-cloud-keyring

    - name: Add OpenStack Repositories
      shell: add-apt-repository cloud-archive:{{ openstack_release }}

    - name: Update packages
      apt: update_cache=yes upgrade=dist cache_valid_time=86400
    
    - name: Install Openstack Client
      apt:
        state: present
        pkg:
          - python3-openstackclient
        
  tasks:
       - include: tasks/common.yml
       - include: tasks/credentials.yml
###############################################################################"
- hosts: controller
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    -  include: tasks/chrony-controller.yml
    -  include: tasks/database-server.yml
    -  include: tasks/rabbitmq-server.yml
    -  include: tasks/memcached.yml
    -  include: tasks/etcd.yml
    -  include: tasks/keystone.yml
    -  include: tasks/glance.yml
    -  include: tasks/placement.yml
    -  include: tasks/nova-controller.yml
    -  include: tasks/neutron-controller.yml
#    -  include: tasks/horizon.yml
    -  include: tasks/nfs-server.yml

- hosts: compute_group
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    -  include: tasks/chrony-compute.yml
    -  include: tasks/nova-compute.yml
    -  include: tasks/neutron-compute.yml
    -  include: tasks/nfs-client.yml
#-  include: tasks/libvirt.yml
    -  include: tasks/compute_node_live_migration_config.yml

- hosts: controller
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    -  include: tasks/create-networks.yml
    -  include: tasks/create-instances.yml

