---
###############################################################################
# This ansible playbook installs all supporting software necessary to run the
# ironic service locally into the vagrant VM attached. Its intent is to provide
# a quickstart development environment that doesn't pollute an engineer's own
# machine.
#
# The vagrant vm's IP address is assumed to be 192.168.99.11
#
# http://docs.openstack.org/developer/ironic/dev/dev-quickstart.html#exercising-the-services-locally
#
- hosts: samsara
  sudo: yes
  tasks:  
    ############################################################################
    # Add OpenStack Repositories
    ############################################################################
    - name: Add OpenStack Repositories
      shell: sudo add-apt-repository -y cloud-archive:kilo
      
     #apt_repository: repo='cloud-archive:kilo'
     #               update_cache=yes
    ############################################################################
    # APT Updates
    ############################################################################
    # Make sure our VM's software is ~@Latest
    - name: Apt Update
      apt: update_cache=yes
           upgrade=dist
           cache_valid_time=86400

    # Reboot if required.
    - name: Reboot system if required
      command: shutdown -r now 'Rebooting to complete system upgrade'
               removes=/var/run/reboot-required
      register: rebooted
    - name: Wait for VM Reboot.
      sudo: no
      local_action: wait_for
                    port=22
                    host="{{ip}}"
                    search_regex=OpenSSH
                    delay=10
                    timeout=900
      when: rebooted.changed
    ############################################################################
    # Install all the needed packages in one go.
    ############################################################################
    - name: Install Required Packages
      apt: name={{item}}
           state=present
      with_items:
      - uvtool
      - uvtool-libvirt
      - qemu-kvm
      - python-libvirt
      - python-dev
      - python-oslo.config
      - virtinst
      - python-pip
      - git
      - htop
      - rabbitmq-server
    ############################################################################
    # Install Required PIP Packages
    ############################################################################
    - name: Install Required PIP Packages
      pip: name={{item}}
      with_items:
      - openstacksdk
      - oslo.config
      - oslo.log
	  - oslo.messaging
      - psutil
      - subprocess32
      - dataset
     ###########################################################################
     # Add user to server and assign full access control
     ###########################################################################
      - rabbitmq_user: user=samsara
                       password=samsara
                       vhost=/
                       configure_priv=.*
                       read_priv=.*
                       write_priv=.*
                       state=present
