---
###############################################################################
# This ansible playbook installs all supporting software necessary to run the
# OpenStack Samsara service locally into the vagrant VM attached. Its intent is to provide
# a quickstart development environment that doesn't pollute an engineer's own
# machine.
#
- hosts: controller
  gather_facts: yes
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/launch-instances-1.yml
    - include: tasks/start-simp.yml
    - include: tasks/launch-instances-2.yml
