- name: Add user vagrant to libvirtd
  sudo: yes
  user: name=vagrant group=libvirtd

# - name: Add user samsara to libvirtd
#   sudo: yes
#   user: name=vagrant group=libvirtd

- name: Restart Nova Compute Services
  sudo: yes
  service: name={{ item }} state=restarted
  with_items:
      - nova-compute
      - nova-network
      - nova-api-metadata
      - libvirt-bin
