# Fix cpuacct not mounted issue
# Todo: to explain more

- name: Creates /sys/fs/cgroup/cpuacct directory
  file: path=/sys/fs/cgroup/cpuacct state=directory owner=root

- name: Creates /sys/fs/cgroup/cpu directory
  file: path=/sys/fs/cgroup/cpu state=directory owner=root

- name: Test for /etc/fstab entry
  shell: grep -c "^cgroup_cpuacct" /etc/fstab || true
  register: test_entry

- name: Add cpuacct entry to /etc/stab
  lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
  with_items:
    - cgroup_cpuacct /sys/fs/cgroup/cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
    - none /sys/fs/cgroup/cpu cgroup cpu 0 0
  when: test_entry.stdout == "0"

- name: Remount device
  become: yes
  shell: mount -av
  ignore_errors: true

- name: Restart Nova Compute and libvirt Services
  become: yes
  service: name={{ item }} state=restarted
  with_items:
      - nova-compute
      - libvirtd