###############################################################################
# Create Databases, users and permissions
###############################################################################

- name: Create Databases
  become: yes
  become_user: postgres
  postgresql_db: name=samsara

- name: Create Users
  become: yes
  become_user: postgres
  postgresql_user: name=samsara password=samsara state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide users with DB permissions
  become: yes
  become_user: postgres
<<<<<<< HEAD
  postgresql_user: user=samsara db=samsara priv=ALL
=======
  postgresql_user: user=samsara db=samsara priv=ALL
>>>>>>> fb7413f4f580e01e4c7844732489db312e5bb253
