############################################################################
# Install all the needed packages in one go.
############################################################################
- name: Install Required Packages
  apt: name={{item}}
       state=present
  with_items:
  - stress-ng
  - multitail
