# - name: Create samsara user
#   environment: "{{ admin_env }}"
#   command: openstack user create --password "{{ samsara_password }}" samsara

# O usuário samsara está sendo criado no deploy do OS.

- name: Add admin role to Samsara user and service project
  environment: "{{ admin_env }}"
  command: openstack role add --project service --user samsara admin

- name: Create Samsara Service Entity
  environment: "{{ admin_env }}"
  command: openstack service create --name samsara --description "OpenStack Samsara" workload