- name: Create Samsara user
  environment: "{{ admin_env }}"
  os_user:
      - state: present
      - name: samsara
      - password: "{{ samsara_password }}"
      - domain: default
      - default_project: demo



- name: Add admin role to nova user and service project
  environment: "{{ admin_env }}"
  command: openstack role add --project service --user samsara admin
  run_once: true

- name: Create Service Entity Nova
  environment: "{{ admin_env }}"
  command: openstack service create --name samsara --description "OpenStack Samsara" workload
  run_once: true

# Create 'Nano' flavor with 256MB of RAM, 1 virtual CPU, and 0GB of
# local disk, and 0GB of ephemeral.
- name: Create Nano flavor
  os_nova_flavor:
      - state: present
      - name: nano
      - ram: 256
      - vcpus: 1
      - disk: 0
      - ephemeral: 0

# Create 'Pico' flavor with 128MB of RAM, 1 virtual CPU, and 0GB of
# local disk, and 0GB of ephemeral.
- name: Create Pico flavor
  os_nova_flavor:
      - state: present
      - name: pico
      - ram: 128
      - vcpus: 1
      - disk: 0
      - ephemeral: 0
      - is_public: True










# Delete 'tiny' flavor
- os_nova_flavor:
    cloud=mycloud
    state=absent
    name=tiny
