- name: Create Samsara group
  group: name=samsara state=present system=yes

- name: Create Samsara user
  user: name=samsara comment="OpenStack Samsara" group=samsara system=yes  createhome=no state=present

- name: Creates /etc/samsara directory
  file: path=/etc/samsara state=directory owner=samsara group=samsara mode=0775 recurse=yes

- name: Creates /var/lock/samsara directory
  file: path=/var/lock/samsara state=directory owner=samsara group=samsara mode=0775 recurse=yes

- name: Creates /var/log/samsara directory
  file: path=/var/log/samsara state=directory owner=samsara group=samsara mode=0775 recurse=yes

- name: Creates /var/run/samsara directory
  file: path=/var/run/samsara state=directory owner=samsara group=samsara mode=0775 recurse=yes