
# Add the group samsara
- name: Create Samsara group
  group: name=samsara state=present system=yes

# Add the user samsara
- name: Create Samsara user
  user: name=samsara comment="OpenStack Samsara" group=samsara system=yes  createhome=no state=present

# Create /etc/samsara directory
- name: Creates /etc/samsara directory
  file: path=/etc/samsara state=directory owner=samsara group=samsara mode=0775 recurse=yes

# Create /etc/samsara/rules directory
- name: Creates /etc/samsara/rules directory
  file: path=/etc/samsara/rules state=directory owner=samsara group=samsara mode=0775 recurse=yes

# Create /var/lock/samsara directory
- name: Creates /var/lock/samsara directory
  file: path=/var/lock/samsara state=directory owner=samsara group=samsara mode=0775 recurse=yes

# Create /var/log/samsara directory
- name: Creates /var/log/samsara directory
  file: path=/var/log/samsara state=directory owner=samsara group=samsara mode=0775 recurse=yes

# Create /var/run/samsara directory
- name: Creates /var/run/samsara directory
  file: path=/var/run/samsara state=directory owner=samsara group=samsara mode=0775 recurse=yes

# # Create a 2048-bit SSH key for user samsara in ~jsmith/.ssh/id_rsa
# - name: Create SSH key
#   user: name=samsara generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
