---
- name: Config Memcached in Controller Node
- hosts: controller
  gather_facts: yes
  become: yes
  user: vagrant
  vars_files:
    - vars/main.yml
  handlers:
    - handlers/main.yml
  tasks:
    - name: Install Memcached packages
      apt: pkg=memcached state=present

    - name: Add reference to Controller Node
      lineinfile:
        path: /etc/memcached.conf
        regexp: '^-l\s127.0.0.1$'
        line: -l {{ ansible_all_ipv4_addresses[1] }}
      notify: restart memcached
