---
###############################################################################
# This ansible playbook installs all supporting software necessary to run the
# OpenStack service locally into the vagrant VM attached. Its intent is to provide
# a quickstart development environment that doesn't pollute an engineer's own
# machine.
#
# The vagrant vm's IP address is assumed to be 192.168.99.11
- hosts: all
  sudo: true
  vars:
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

    # Add OpenStack Repositories
    - name: Add OpenStack Repositories
      shell: sudo add-apt-repository -y cloud-archive:kilo

    # Make sure our VM's software is ~@Latest
    - name: Apt Update
      apt: update_cache=yes
           upgrade=dist
           cache_valid_time=86400

    # Reboot if required.
    - name: Reboot system if required
      command: shutdown -r now 'Rebooting to complete system upgrade'
           removes=/var/run/reboot-required
      register: rebooted
    - name: Wait for VM Reboot.
      sudo: no
      local_action: wait_for
                    port=22
                    host="{{ip}}"
                    search_regex=OpenSSH
                    delay=10
                    timeout=900
       when: rebooted.changed


###############################################################################
  roles:
    - webserver
    - database
