---
###############################################################################
# This ansible playbook installs all supporting software necessary to run the
# OpenStack Samsara service locally into the vagrant VM attached. Its intent is to provide
# a quickstart development environment that doesn't pollute an engineer's own
# machine.
#
- hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/system-config.yml
    - include: tasks/install-deps.yml
    - include: tasks/samsara-common-config.yml
    - include: tasks/samsara-rules-config.yml
    - include: tasks/install-samsara.yml
###############################################################################
- hosts: controller
  gather_facts: yes
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
      - include: tasks/database-server.yml
      - include: tasks/openstack-config-setup.yml
      - include: tasks/samsara-cell-rules.yml
      # - include: tasks/start-samsara-controller-node.yml
- hosts: compute_group
  gather_facts: yes
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
      - include: tasks/rootwrap-config.yml
      - include: tasks/add-users-to-libvirtd-group.yml
      - include: tasks/samsara-hosts-rules.yml
      - include: tasks/install-compute-nodes-tools.yml
      - include: tasks/start-samsara-compute-node.yml
#      - include: tasks/cpuacct-ubuntu-fix.yml
