---
###############################################################################
# This ansible playbook installs all supporting software necessary to run the
# OpenStack Samsara service locally into the vagrant VM attached. Its intent is to provide
# a quickstart development environment that doesn't pollute an engineer's own
# machine.
#
- hosts: all
  gather_facts: no
  sudo: true
  vars_files:
      - vars.yml
      - ../openstack/vars.yml
  tasks:
       - include: tasks/system-config.yml
###############################################################################
- hosts: controller
  sudo: true
  vars_files:
      - vars.yml
      - ../openstack/vars.yml
  handlers:
      #- include: handlers/main.yml
  tasks:
      #- include: tasks/database-server.yml
      - include: tasks/openstack-config-setup.yml
      - include: tasks/install-deps.yml
      - include: tasks/samsara-controller-config.yml

- hosts: compute_group
  sudo: true
  vars_files:
      - vars.yml
      - ../openstack/vars.yml
  tasks:
      - include: tasks/install-deps.yml
      - include: tasks/rootwrap-config.yml
      - include: tasks/samsara-compute-config.yml
