- include_tasks: create-provider-network.yml
  tags:
    create-networks

- include_tasks: create-selfservice-network.yml
  tags:
    create-networks

- name: Enable ICPM to default Security Group
  environment: "{{ admin_env }}"
  os_security_group_rule:
    security_group: default
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0

- name: Enable SSH to default Security Group
  environment: "{{ admin_env }}"
  os_security_group_rule:
    security_group: default
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0