- name: Generate SSH Key
  environment: "{{ admin_env }}"
  openssh_keypair:
    path: /home/vagrant/.ssh/id_rsa
    owner: vagrant
    group: root
  register: new_ssh_key

- name: Add public keypair
  environment: "{{ admin_env }}"
  os_keypair:
    state: present
    name: mykey
    public_key_file: /home/vagrant/.ssh/id_rsa.pub
  when: new_ssh_key is changed

- name: Launch Instances in SelfService Network
  environment: "{{ admin_env }}"
  os_server:
    state: present
    name: "{{ item }}"
    image: cirros
    key_name: mykey
    timeout: 200
    flavor: nano
    network: selfservice
  with_items:
    - instance_000
    - instance_001
    - instance_002

- name: Add Floating IPs to Instances
  environment: "{{ admin_env }}"
  os_floating_ip:
    state: present
    server: "{{ item }}"
    timeout: 200
    wait: true
    network: provider
    nat_destination: selfservice
  with_items:
    - instance_000
    - instance_001
    - instance_002
