- name: change hosts
  become: yes
  template: src=hosts.j2 dest=/etc/hosts
  tags:
    - build_hosts

- name: Config NICs
  become: yes
  template: src=50-vagrant.yaml.j2 dest=/etc/netplan/50-vagrant.yaml
  notify: netplan apply

- name: Install Chrony package
  become: yes
  apt: pkg=chrony state=present

- name: Update Timezone to Etc/UTC
  copy: content="America/Sao_Paulo\n" dest=/etc/timezone owner=root group=root mode=0644
  become: yes
  register: timezone

- name: Reconfigure Timezone Data
  shell: dpkg-reconfigure -f noninteractive tzdata
  become: yes
  when: timezone.changed
