- name: Install etcd packages
  become: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - etcd
  notify: enable etcd
  tags:
    - etcd

- name: Config etcd
  become: yes
  template: src=etcd.j2 dest=/etc/default/etcd
  notify: restart etcd
  tags:
    - etcd