- name: Install etcd packages
  become: yes
  apt: pkg=etcd state=present update_cache=yes
  notify: enable etcd
  tags:
    - etcd

- name: Config etcd
  become: yes
  template: src=etcd.j2 dest=/etc/default/etcd
  notify: restart etcd
  tags:
    - etcd