- name: Create glance user
  environment: "{{ admin_env }}"
  command: openstack user create --domain default --password "{{ openstack_users.glance_password }}" glance
  register: check_glance_create_user
  changed_when: False
  tags:
    - glance

- name: Add admin role to glance user and service project
  environment: "{{ admin_env }}"
  command: openstack role add --project service --user glance admin
  register: check_glance_add_glance_to_admin_role
  changed_when: False
  tags:
    - glance

- name: Create Service Entity Glance
  environment: "{{ admin_env }}"
  command: openstack service create --name glance --description "OpenStack Image service" image
  register: check_glance_identity
  changed_when: False
  tags:
    - glance

- name: Create Glance Service Endpoint
  environment: "{{ admin_env }}"
  command: openstack endpoint create --publicurl http://controller:9292 --internalurl http://controller:9292 --adminurl http://controller:9292 --region RegionOne image
  register: check_glance_endpoint
  changed_when: False
  tags:
    - glance

- name: Install Glance packages
  become: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
      - glance
#- python-glanceclient
  tags:
    - glance

- name: Copy Glance API config file
  template:
      src: "glance-api.conf.j2"
      dest: "/etc/glance/glance-api.conf"
      owner: root
      group: root
      mode: 0644
  tags:
    - glance

- name:  Glance DB Populate
  become: yes
  shell: su -s /bin/sh -c "glance-manage db_sync" glance
  register: check_glance_db_populate
  changed_when: False
  tags:
    - glance

- name: Restart Glance API
  become: yes
  service: name=glance-api state=restarted
  tags:
    - glance

- name: Get Cirros Image
  shell: wget -P /tmp/cirros-0.4.0-x86_64-disk.img http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
  register: check_cirros_download
  changed_when: False
  tags:
    - glance

- name: Create Image for Cirros
  environment: "{{ admin_env }}"
  shell: glance image-create --name "cirros" --file cirros-0.4.0-x86_64-disk.img  --disk-format qcow2 --container-format bare --visibility public
  register: check_cirros_create
  changed_when: False

- name: Get Glance Image List
  environment: "{{ admin_env }}"
  command: glance image-list

- name: Remove Cirros Image
  shell: rm /tmp/cirros-0.4.0-x86_64-disk.img
  register: check_remove_cirros
  changed_when: False
