- name: Install Horizon packages
  become: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
      - openstack-dashboard

- name: Copy Horizon Config File Template
  template: src=local_settings.py dest=/etc/openstack-dashboard/local_settings.py

- name: restart apache
  become: yes
  service: name=apache2 state=restarted
