- name: Install Keystone packages
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
      - keystone
      - python3-openstackclient
  tags:
    - keystone

- name: Copy Keystone config file
  become: yes
  template:
      src: "keystone.conf.j2"
      dest: "/etc/keystone/keystone.conf"
      owner: root
      group: root
      mode: 0644
  tags:
    - keystone

- name: Populate the Identity service database
  become: yes
  shell: /bin/sh -c "keystone-manage db_sync" keystone
  tags:
    - keystone

- name: Refs to Controller Node
  lineinfile:
      dest:  "/etc/apache2/apache2.conf"
      regexp: "^ServerName "
      line: "ServerName controller"
  notify: restart apache
  tags:
    - keystone

- name: Initialize Fernet key repositories
  become: yes
  shell:
    cmd: "{{ item }}"
  with_items:
    - keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
    - keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  tags:
    - keystone
  
- name: Bootstrap Identity service
  become: yes
  shell: keystone-manage bootstrap --bootstrap-password {{ openstack_users['admin_password'] }} --bootstrap-admin-url http://controller:5000/v3/ --bootstrap-internal-url http://controller:5000/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne
  tags:
    - keystone

- name: Create Service Project
  environment: "{{ admin_env }}"
  command: openstack project create --domain default --description "Service Project" service
  ignore_errors: true