- name: Install Keystone packages
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
      - keystone
      - python3-openstackclient
      # - apache2
      # - libapache2-mod-wsgi
      # - memcached
      # - python-memcache
  tags:
    - keystone

# - name: Disable Keystone autostart
#   become: yes
#   shell: su -c 'echo "manual" > /etc/init/keystone.override'
#   tags:
#     - keystone

- name: Copy Keystone config file
  become: yes
  template:
      src: "keystone.conf.j2"
      dest: "/etc/keystone/keystone.conf"
      owner: root
      group: root
      mode: 0644
  tags:
    - keystone

- name: Populate the Identity service database
  become: yes
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
  tags:
    - keystone

- name: Refs to Controller Node
  lineinfile:
      dest:  "/etc/apache2/apache2.conf"
      regexp: "^ServerName "
      line: "ServerName controller"
  notify: restart apache
  tags:
    - keystone

- name: Initialize Fernet key repositories
  become: yes
  shell:
    cmd: "{{ item }}"
  with_items:
    - keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
    - keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  tags:
    - keystone
  
- name: Bootstrap Identity service
  become: yes
  shell: keystone-manage bootstrap --bootstrap-password {{ openstack_users['admin_password'] }} --bootstrap-admin-url http://controller:5000/v3/ --bootstrap-internal-url http://controller:5000/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne
  tags:
    - keystone

- name: Create Service Project
  environment: "{{ admin_env }}"
  command: openstack project create --domain default --description "Service Project" service
  ignore_errors: true

- name: Create Samsara User
  environment: "{{ admin_env }}"
  command: openstack user create --domain default --password {{ openstack_users['samsara_password'] }} samsara
  register: create_samsara_user
  ignore_errors: true

- name: Create Samsara Demo Project
  environment: "{{ admin_env }}"
  command: openstack project create --domain default --description "Demo Project" samsaraproject
  when: create_samsara_user is succeeded

- name: Create Samsara Role
  environment: "{{ admin_env }}"
  command: openstack role create samsararole
  when: create_samsara_user is succeeded

- name: Add Samsara Role to Samsara User
  environment: "{{ admin_env }}"
  command: openstack role add --project samsaraproject --user samsara samsararole
  when: create_samsara_user is succeeded
