- name: Install Libvirt packages
  become: yes
  apt:
    state: present 
    pkg:
      - libvirt-daemon-system
      - libvirt-clients
      - qemu-kvm
  tags:
    - libvirt
    
- name: Libvirt System Socket Activation
  become: yes
  shell: systemctl start libvirtd-tcp.socket
  tags:
    - libvirt

- name: Restart Nova-compute and Libvirtd
  become: yes
  service: name={{ item }} state=restarted
  with_items:
      - libvirtd
      - nova-compute
  tags:
    - libvirt
