- name: Copy nova-compute config file
  template:
      src: "nova-compute.conf.j2"
      dest: "/etc/nova/nova-compute.conf"
      owner: root
      group: root
      mode: 0644
  tags:
    - nova-live-migration

- name: Restart Nova-compute and Libvirtd
  become: yes
  service: name={{ item }} state=restarted
  with_items:
      - libvirtd
      - nova-compute
  tags:
   - nova-live-migration