- name: Create Neutron user
  environment: "{{ admin_env }}"
  command: openstack user create --password "{{ openstack_users.neutron_password }}" neutron
  register: neutron_create_user
  ignore_errors: true
  tags:
    - neutron-controller

- name: Add admin role to Neutron user and service project
  environment: "{{ admin_env }}"
  command: openstack role add --project service --user neutron admin
  when: neutron_create_user is succeeded
  tags:
    - neutron-controller

- name: Create Service Entity Neutron
  environment: "{{ admin_env }}"
  command: openstack service create --name neutron --description "OpenStack Networking" network
  when: neutron_create_user is succeeded
  tags:
    - neutron-controller

- name: Create Neutron Service Endpoint
  environment: "{{ admin_env }}"
  command: openstack endpoint create --region RegionOne network {{ item }} http://controller:9696 
  with_items:
    - public
    - internal
    - admin  
  when: neutron_create_user is succeeded
  tags:
    - neutron-controller

- name: Install Neutron Controller packages
  become: yes
  apt:
    state: present
    update_cache: yes
    pkg:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-l3-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
  tags:
    - neutron-controller

- name: Copy Neutron config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
   - { src: "neutron-controller.conf.j2", dest: "/etc/neutron/neutron.conf" }
   - { src: "ml2_conf.ini.j2", dest: "/etc/neutron/plugins/ml2/ml2_conf.ini" }
   - { src: "linuxbridge_agent.ini.j2", dest: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini"}
   - { src: "l3_agent.ini.j2", dest: "/etc/neutron/l3_agent.ini" }
   - { src: "dhcp_agent.ini.j2", dest: "/etc/neutron/dhcp_agent.ini" }
   - { src: "metadata_agent.ini.j2", dest: "/etc/neutron/metadata_agent.ini" }
   - { src: "nova-controller.conf.j2", dest: "/etc/nova/nova.conf" }
  tags:
    - neutron-controller

- name: Neutron DB Populate
  become: yes
  environment: "{{ admin_env }}"
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  tags:
    - neutron-controller

- name: Restart Nova API and Neutron services
  become: yes
  service: name={{ item }} state=restarted
  with_items:
      - nova-api
      - neutron-server
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
      - neutron-l3-agent
  tags:
    - neutron-controller
