- name: Install NFSv4 Client package
  sudo: yes
  apt: pkg=nfs-common state=installed

- name: Add Nova instances folder to FSTAB
  sudo: yes
  shell: |
    su -c "cat >> /etc/fstab << EOF
                # NFS - Nova work directory
                172.16.0.10:/ /var/lib/nova/instances nfs4 defaults 0 0
            EOF
            "

- name: Remount device
  sudo: yes
  shell: mount -av

# This enable the ‘execute/search’ bit on your shared directory to allow qemu to be able to use the images within the directories
- name: Change Nova instances folder permissions.
  file: path=/var/lib/nova/instances owner=nova group=nova recurse=yes
