- name: Install NFSv4 Client package
  become: yes
  apt: pkg=nfs-common state=present
  tags:
    - nfs

- name: Test for /etc/fstab entry
  shell: grep -c "^192.168.56.10" /etc/fstab || true
  register: test_entry
  tags:
    - nfs

- name: Add Nova instances folder to FSTAB
  lineinfile:
    path: /etc/fstab
    line: 192.168.56.10:/ /var/lib/nova/instances nfs4 defaults 0 0
  when: test_entry.stdout == "0"
  tags:
    - nfs

- name: Remount device
  become: yes
  shell: mount -av
  tags:
    - nfs

# This enable the ‘execute/search’ bit on your shared directory to allow qemu to be able to use the images within the directories
- name: Change Nova instances folder permissions.
  file: path=/var/lib/nova/instances owner=nova group=nova recurse=yes
  tags:
    - nfs
