- name: Install Nova Compute packages
  become: yes
  apt: pkg=nova-compute state=present
  tags:
    - nova-compute

- name: Copy Nova Compute config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - {src: "nova.conf-compute.j2", dest: "/etc/nova/nova.conf" }
    - {src: "nova-compute.conf.j2", dest: "/etc/nova/nova-compute.conf" }
  tags:
    - nova-compute

- name: Restart Nova Compute Services
  become: yes
  service: name=nova-compute state=restarted
  tags:
    - nova-compute
