- name: Install Nova Compute packages
  become: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
      - nova-compute
  tags:
    - nova-compute

- name: Copy Nova Compute config files
  template:
    src: {{ item.src }}
    dest: {{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - {"nova.conf-compute.j2", dest: "/etc/nova/nova.conf" }
    - {"nova-compute.j2", dest: "/etc/nova/nova-compute.conf" }
  tags:
    - nova-compute

- name: Restart Nova Compute Services
  become: yes
  service: name={{ item }} state=restarted
  with_items:
      - nova-compute
  tags:
    - nova-compute
