- name: Create Placement user
  environment: "{{ admin_env }}"
  command: openstack user create --domain default --password "{{ openstack_users.placement_password }}" placement
  ignore_errors: true
  register: placement_create_user
  tags:
    - placement

- name: Add admin role to Placement user and service project
  environment: "{{ admin_env }}"
  command: openstack role add --project service --user placement admin
  when: placement_create_user is succeeded
  tags:
    - placement

- name: Create the Placement API entry in the service catalog
  environment: "{{ admin_env }}"
  command: openstack service create --name placement --description "Placement API" placement
  when: placement_create_user is succeeded
  tags:
    - placement

- name: Create the Placement API service endpoints
  environment: "{{ admin_env }}"
  command: openstack endpoint create --region RegionOne placement {{ item }} http://controller:8778
  with_items:
    - public
    - internal
    - admin
  when: placement_create_user is succeeded
  tags:
    - placement

- name: Install Placement packages
  become: yes
  apt: pkg=placement-api state=present update_cache=yes
  tags:
    - placement

- name: Copy Placement API config file
  template:
      src: "placement.conf.j2"
      dest: "/etc/placement/placement.conf"
      owner: root
      group: root
      mode: 0644
  tags:
    - placement

- name:  Placement DB Populate
  become: yes
  shell: su -s /bin/sh -c "placement-manage db sync" placement
  notify: restart apache
  tags:
    - placement

# Restart apache
