- name: Install Postgresql packages
  become: yes
  apt:
    state: present
    pkg:
      - libpq-dev # Required for Ansible to interact with postgres
      - python3-psycopg2 # Required for Ansible to interact with postgres
