- name: Install RabbitMQ package
  become: yes
  apt: pkg=rabbitmq-server state=present update_cache=yes
  tags:
    - rabbitmq-server

- name: Add user to server and assign full access control
  rabbitmq_user: user={{ rabbitmq.user }}
                 password={{ rabbitmq.password }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  tags:
    - rabbitmq-server
