- name: restart postgresql
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: start simp
  shell: cd /home/vagrant/samsara/simp/simp/ && sudo -u samsara python3 simp_monitor.py